version: '3'

services:
  nginx:
    image: nginx
    volumes:
      - ./:/var/www/
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d/
    ports:
      - "8081:80"
    depends_on:
      - app
  app:
    build:
        context: .
        dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www/


